# Generated by Django 3.2.4 on 2021-07-01 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('correo', models.EmailField(max_length=254)),
                ('curso', models.CharField(max_length=20)),
                ('mensaje', models.TextField()),
                ('phone', models.IntegerField()),
                ('imagen', models.ImageField(null=True, upload_to='fotos', verbose_name='Picture')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
