# Generated by Django 3.2.4 on 2021-08-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_auto_20210804_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeUsuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Usuario')),
                ('nombre', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('curso', models.TextField()),
                ('telefono', models.IntegerField()),
                ('mensaje', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mensaje usuario',
                'verbose_name_plural': 'Mensajes usuarios',
                'ordering': ['-created'],
            },
        ),
    ]
