# Generated by Django 3.2.4 on 2021-08-06 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_alter_cursos_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id curso'),
        ),
    ]
